---
sidebar: sidebar 
permalink: create-workspaces.html 
keywords: manage, workspace, snapshot, project 
summary: 'Un espace de travail dans NetApp Workload Factory for Builders est une représentation Perforce d"un projet basé sur un instantané de projet.  Vous pouvez créer des espaces de travail dans le cadre d"un projet Builders.' 
---
= Créez un espace de travail Builders
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un espace de travail dans NetApp Workload Factory for Builders est une représentation Perforce d'un projet à un moment précis.  Les espaces de travail sont créés en utilisant un instantané de projet comme base.  Vous pouvez créer de nouveaux espaces de travail dans un projet Builders.  Vous pouvez créer des espaces de travail à partir de l'interface utilisateur Perforce.

.Avant de commencer
Assurez-vous d'avoir intégré Builders au client visuel Perforce Helix. Voir link:integrate-perforce.html["Intégrez des constructeurs à Perforce"^] pour plus d'informations.

.Étapes
. Connectez-vous à Perforce.
. Dans le menu Perforce, sélectionnez *View* > *WF*.
+
L'écran de connexion de Workload Factory apparaît dans l'interface utilisateur Perforce.

. Connectez-vous à Workload Factory en utilisant l'un deslink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^] .
. Dans la mosaïque Charges de travail des constructeurs, sélectionnez *Créer un projet*.
. Sélectionnez *Créer un espace de travail*.
. Sur la page Créer un projet d'espace de travail, fournissez les informations suivantes :
+
.. Sélectionnez un instantané à utiliser comme base pour l'espace de travail.
.. Entrez un nom pour l'espace de travail.
.. Vous pouvez également saisir un identifiant utilisateur pour demander l'espace de travail. Cet identifiant doit correspondre à l'ID utilisateur Perforce du développeur qui utilisera cet espace de travail.


. Sélectionnez *Créer*.


.Résultat
L'espace de travail est créé et apparaît dans la liste des espaces de travail de la page espaces de travail.
