---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: 'NetApp Workload Factory for Builders est un outil de création d"environnement de construction rapide pour les créateurs de logiciels.' 
---
= En savoir plus sur NetApp Workload Factory pour les constructeurs
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders est un outil de création d'environnement de construction rapide pour les créateurs de logiciels.  Il permet une configuration rapide des environnements de développement personnel, ce qui permet de gagner du temps et d'activer le libre-service pour les développeurs tout en permettant aux équipes DevOps de conserver le contrôle de l'infrastructure.  Grâce à Builders, les développeurs de logiciels peuvent créer rapidement des espaces de travail sans avoir besoin d'un stockage de données spécialisé ni d'une compréhension de l'infrastructure de développement.



== Qu'est-ce que NetApp Workload Factory pour les constructeurs ?

NetApp Workload Factory for Builders est conçu pour simplifier la manière dont les développeurs gèrent et interagissent avec les différentes versions de leurs logiciels. Builders fonctionne avec Perforce Helix Core pour cloner instantanément les versions logicielles et créer des espaces de travail pour le développement, l'assurance qualité et l'intégration continue/la livraison continue.

Avec Builders, vous pouvez facilement créer un projet et lui attribuer un volume qui représente votre environnement logiciel et ses artefacts. Lors de la mise à jour de votre logiciel, vous pouvez prendre des instantanés du volume, capturant ainsi l'état de votre logiciel à ce moment précis. Vous pouvez accéder instantanément à n'importe quelle version du logiciel sans resynchronisation, ce qui vous permet de gagner du temps et des ressources.

Grâce aux fonctionnalités de snapshot et de clonage de NetApp ONTAP, Builders permet d'accéder plus rapidement aux différentes versions de votre logiciel, ce qui vous permet de développer et de publier des mises à jour plus rapidement.

Pour plus d'informations sur Workload Factory, reportez-vous aulink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Présentation de Workload Factory"^] .



== Fonctionnalités de NetApp Workload Factory pour les constructeurs

NetApp Workload Factory for Builders offre les fonctionnalités suivantes :

* Créer, modifier et supprimer des projets
* Créer des instantanés des versions logicielles définies
* Création et suppression d'espaces de travail (basés sur des clones)
* Créez des stratégies d'accès pour contrôler l'accès à un projet
* Analysez l'utilisation de la capacité de chaque projet
* Contrôlez les limites de taille de clone et la conservation des clones pour chaque projet
* Intégration avec des systèmes de contrôle des versions tels que Perforce




== Projets et espaces de travail dans Builders

Lorsque vous utilisez Builders, vous créez un projet et attribuez un volume qui représente votre environnement logiciel et ses artefacts. Chaque fois que vous créez une nouvelle version du logiciel, vous devez resynchroniser les données de volume et créer un snapshot de projet pour marquer l'état du volume comme une version connue. Le volume source du projet peut recevoir des mises à jour en continu et avoir plusieurs snapshots pour marquer plusieurs versions. Vous pouvez utiliser chaque instantané immédiatement en tant que clone instantané, référentiel modifiable dédié ou partagé disponible pour les développeurs, les processus d'assurance qualité ou de création. Un clone dans le contexte d'une version logicielle spécifique est un espace de travail.



== Automatisation avec Workload Factory Codebox

L'usine de charge de travail intègre l'automatisation avec la _Codebox_. La Codebox offre les avantages d'automatisation suivants :

* *Génération de code snippet* : des snippets IAC (Infrastructure-as-Code) sont générés lors de la création de ressources, permettant une intégration transparente avec les workflows d'orchestration existants.
* *Copilote d'infrastructure en tant que code* : Codebox est un copilote d'infrastructure en tant que code (IaC) qui aide les développeurs et DevOps à générer du code pour exécuter n'importe quelle opération prise en charge par Workload Factory.
* *Afficheur de code et catalogue d'automatisation*: La Codebox fournit un afficheur de code pour une analyse rapide de l'automatisation et un catalogue d'automatisation pour une réutilisation rapide future.




== Le coût

L’utilisation de la fonctionnalité Builders de Workload Factory est gratuite.



== Licences

Aucune licence spéciale n'est requise auprès de NetApp pour utiliser les fonctionnalités Builders de Workload Factory.



== Régions

Les constructeurs sont pris en charge dans toutes les régions commerciales où FSX pour ONTAP est pris en charge. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Affichez les régions Amazon prises en charge."^]

Les régions AWS suivantes ne sont pas prises en charge :

* Régions de Chine
* GovCloud (USA)
* Le cloud secret
* Meilleur cloud secret




== Obtenir de l'aide

Amazon FSx for NetApp ONTAP est une solution AWS propriétaire. Pour obtenir de l'aide, utilisez le Centre de support de votre console de gestion AWS pour ouvrir un ticket. Sélectionnez « FSx pour ONTAP» et la catégorie, puis fournissez les informations requises.

Pour des questions générales sur Workload Factory ou les applications et services Workload Factory, reportez-vous àlink:get-help-builders.html["Obtenez de l'aide pour les constructeurs de Workload Factory"] .
