---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, Workload Factory, builders, Workload Factory' 
summary: Découvrez les nouveautés de Workload Factory pour les bases de données. 
---
= Nouveautés de NetApp Workload Factory pour les constructeurs
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la fonctionnalité Builders de Workload Factory.



== 5 octobre 2025



=== BlueXP workload factory désormais NetApp Workload Factory

BlueXP a été renommé et repensé pour mieux refléter le rôle qu'il joue dans la gestion de votre infrastructure de données.  Par conséquent, BlueXP workload factory a été renommée NetApp Workload Factory.



== 16 juin 2025



=== Prise en charge du clonage

Vous pouvez désormais cloner un projet dans BlueXP Workload Factory for Builders.  Lorsque vous clonez un projet, Builders crée un nouveau projet à partir d'un instantané, avec la même configuration que l'original.  Le clonage est utile pour créer rapidement des projets similaires ou à des fins de test.  Vous pouvez monter le nouveau clone du projet en suivant les instructions dans Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Gérer les versions des projets BlueXP Workload Factory for Builders"]



== 4 mai 2025



=== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de Workload Factory utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



== 1 décembre 2024



=== Création de la version initiale de la charge de travail

BlueXP Workload Factory for Builders simplifie la consommation et l'accès aux versions logicielles, éliminant ainsi le besoin d'outils ou de scripts personnalisés.  Il vous permet de consommer des versions logicielles sous forme de clones instantanés intégrés à Perforce Helix Core comme espace de travail pratique pour vos processus de développement, économisant ainsi du temps et des ressources.

La version initiale permet de gérer des projets et des espaces de travail, et d'automatiser les actions avec Codebox. Vous pouvez également intégrer Builders à Perforce Helix Core, afin de gérer différentes versions de chaque projet et de passer rapidement de l'une à l'autre.
